export const APIURL = 'http://localhost:9991'
export const PUB_KEY = '-----BEGIN PUBLIC KEY-----\n' +
  'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCd8I5SyQR2S5K+K3umU2LNRCGDddbjx9UApfxF\n' +
  'VXPvQRUfANteA8je4FHJyX3aE8qu30ODlX9ESPkZcsD6jRzsGH6/3NMnw70CyDEsQeK00HfNKb6J\n' +
  'zF6TLw9bZwcbb03DUxLeLfRZhlPjfbcbqxIp5ePmxsExDqm/JLSW7RSrDQIDAQAB-----END PUBLIC KEY-----';
